# Generated by Django 2.2.28 on 2022-05-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('visits', models.PositiveIntegerField()),
                ('likes', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('views', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('index',),
            },
        ),
    ]
